### ISSUE TITLE
error while running example file

### ISSUE THREAD

**Issue by hites77** [vbrisson/HabitatCorrectedNetwork#1]
command: python HabitatCorrectedNetwork.py -A example_ASV_table.txt -S example.txt -out result1 -s config -sfn example_config.cfg

Error:

Reading OTU table data
Traceback (most recent call last):
  File "HabitatCorrectedNetwork.py", line 542, in <module>
    main()
  File "HabitatCorrectedNetwork.py", line 535, in main
    direction)
  File "HabitatCorrectedNetwork.py", line 334, in HF_analysis
    full_data_array, master_OTU_list, sample_names = read_OTU_table(OTU_filename)
  File "HabitatCorrectedNetwork.py", line 38, in read_OTU_table
    OTU_table = np.vstack((OTU_table, abundances))
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/users/nus/eriht/.local/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 836 and the array at index 1 has size 1

**Comment by nweerasu** [comment]
Running python3, had to change to import configparser at line 17, but otherwise, same error output.
Thanks!

**Comment by nweerasu** [comment]
Hi again,

This was fixed on my end by going down to python 2.7 and uninstalling all previous python packages, then getting pip to install statsmodels==0.10.2 which does not throw the error requiring python>3 (it will error out if you don't specify this older package of statsmodels).
Installing this first also pulls the numpy and scipy packages as well to make an easy single line of code.

I had to separately install configparser: pip install configparser to get the original code to run since I still got the ImportError: No module named configparser.
